### ISSUE TITLE
Keep the Google Maps API key in an external configuration file

### ISSUE THREAD

**Issue by soenkenils** [itm/wiseui#10]
When deploying the WiseUI on our production system we need a Google API key. In the former versions we kept the API key in the code. This shall be avoided.

**Comment by mlegenhausen** [comment]
We could make a ResourceBundle for all configuration parameters.

**Comment by mlegenhausen** [comment]
It can now be created a MapConstants.properties file under eu.wisebed.wiseui.client.util.
API Key, Version and Sensor usage can be configured.
