### ISSUE TITLE
Add famfamfam icons to the GUI

### ISSUE THREAD

**Issue by mlegenhausen** [itm/wiseui#13]
Make the GUI more fancy with the famfamfam icons: http://www.famfamfam.com/lab/icons/silk/

**Comment by soenkenils** [comment]
Do we have an ImageBundle somewhere? Ah, the MessageBox uses one. Ok, this means we have to add a new ImageBundle in the "client" module. Where do we store the images?

**Comment by mlegenhausen** [comment]
I think it is better to add the ImageBundle to the widget module.

**Comment by mlegenhausen** [comment]
FamFamFam Icons added. Free to use with the FamFamFamResources class.
