### ISSUE TITLE
Select nodes via google maps

### ISSUE THREAD

**Issue by ichatz** [itm/wiseui#16]
In addition to having a drop-down list or a tree-view with all the nodes, position the nodes on the google maps and allow the user to click + select. Maybe this will require the g2d. But sounds more reasonable, since some times it is the location that is important rather than the hw specs.

**Comment by mlegenhausen** [comment]
We had this view before, but we decided against this, cause we have testbed where there is only 1 meter between the nodes and the nodes are stacked. So you can nothing see on the map and on bigger testbeds you can only draw a limited amount of nodes. So we decided only to draw the shape of the testbed.

A better idea would be to use webgl to show the nodes in 3d. But the apis are really basic and it would require a little bit more time to get things working.

**Comment by mlegenhausen** [comment]
I will close this issue and it would be better to open new issues with other improvements like a WebGL view.
