### ISSUE TITLE
The loading indicator shall be hidden when an error message appears

### ISSUE THREAD

**Issue by soenkenils** [itm/wiseui#22]
Currently, the loading indicator blocks an error message:

![WiseUI Loading Indicator Problem](http://www.itm.uni-luebeck.de/users/nommensen/wiseui/wiseui_loading_indicator_problem.png)

**Comment by mlegenhausen** [comment]
Seems that the z-index of the loading indicator is too high or the z-index of the popup to low. I will take a look at this.

**Comment by mlegenhausen** [comment]
Fixed by setting z-index to auto.

**Comment by soenkenils** [comment]
Can't you just say something like (see below) ?

`
public void onFailure(Throwable caught) {
   loadingIndicator.hide();
   ...
}
`

**Comment by mlegenhausen** [comment]
I added both, cause it can be that you want to open a dialog box during the loading indicator is shown.

**Comment by mlegenhausen** [comment]
I think it is working as it should. Closed.
