### ISSUE TITLE
Move Persistence Code To A Separate Maven Module

### ISSUE THREAD

**Issue by soenkenils** [itm/wiseui#24]
We should move the persistence stuff to a separate Maven module for a cleaner separation of concerns.

What we could do is:
-   Create a new module "persistence"
-   Use Spring transaction management for persistence transactions (http://stackoverflow.com/questions/1079114/spring-transactional-annotation-best-practice)
-   Move all domain/entity classes to the new module
-   Move DAOs to the new module
-   The persistence module shall provide a service that can be used as GWT-RPC service to store relevant data permanently
-   This way, we also would avoid the several dependencies brought in by the Gilead project usage
-    Map DTOs (Data Transfer Objects, objects, which are transferred to the client) to BOs (Business Objects, which we be stored with Hibernate) with Dozer

What do you think?

I already started the development in a separate branch, which I can share on GitHub if you like.

**Comment by soenkenils** [comment]
I recently noticed that Gilead makes our *.war-file round about 45MB (!!) large because of its many dependencies.

That is another good reason to change the persistence mechanism. I started doing so in our new branch:

https://github.com/itm/wiseui/tree/persistence-refactoring

Ok, Spring-Hibernate isn't for free either, but at least it seems to bring us down to 20MB, which is still quite large but still ok as we are using many 3rd party libraries.

I started to implement a PersistenceService, which shall represent our persistence service layer. Currently it can store and load a TestbedConfiguration, but the code is not used, yet. The service operations are declared as transactional, thus utilizing Spring's transaction management.

I'm using three types of classes:
-  BOs (Business Objects; Plain old Java objects that define a structure to be stored by Hibernate) 
-  DAOs (Data Access Objects; Those objects manage the BOs, e.g. persist and find them) 
-  Services (transactional service layer to be used by the GWT client)

**Comment by iogakos** [comment]
> > I recently noticed that Gilead makes our *.war-file round about 45MB (!!) large because of its many dependencies.

I don't see why this is a good reason to get rid of a library. I understand that build/deploy times might get slight higher, but the advantages of Gilead over Dozer make me forget the size of the jar. I would agree if we were implementing a service where huge data sets are travelling over the wire, when both Gilead and Dozer could induce a remarkable overhead  

You might want to take a look at the integration stategies proposed by Google at http://code.google.com/webtoolkit/articles/using_gwt_with_hibernate.html

**Comment by soenkenils** [comment]
Ok, maybe I have to explain a little more. Yes, I know that Google documentation page about Hibernate and GWT integration. The documentation page gives an overview and of the possibilites for Hibernate integration. They also give some hints about the usage of Data Transfer Objects (DTOs).

But as far as I understood, Gilead is only one of many options they present. In a related note, Dozer has nothing to do with persistence per se! Dozer is a simple bean to bean mapper. It is only used to map DTOs to persistent objects (BOs).

And that is exactly what I did in the new "persistence" module. I relabled the objects in the "shared" module as DTOs, the objects that can be used in the "client" while introducing persistent objects (which I called BOs aka business objects; *Bo.java). The BOs are the objects with the Hibernate annotations. Internally, "persistence" only works with BOs. The "persistence" layer only returns and accepts DTOs in its interface. This way we achieve a clear separation of persistence and the rest of our modules.

And what about transaction management? As far as I know, Gilead does not offer transaction management. As a developer you have to use the HibernateUtil and open and close you transactions manually. This means you have to _manually_ make sure (e.g. using a finally-block) that your transaction is closed, which could be an error-prone programming task. Spring offers annotation-based transaction management with the `@Transactional` annotation. Internally, this is done with aspect oriented programming (AOP), but this is transparent to the developer.

The Google documentation also suggests to offer persistence as a GWT-RPC service, which means persistence operations can be _directly_ called by the client. In my opinion, this is not a good idea. In our project we started to design the GWT-RPC services very task-oriented. As persistence is a very general task (cross-cutting concept), architecturally we need to place it underneath our taks-oriented services. This way our GWT-RPC services, e.g. `TestbedConfigurationService`, can utilize persistence, but at the same time persistence cannot be directly used by the client.

These are the reasons why I prefer the new "persistence" module over the Gilead-based solution. I certainly did not want to offend anyone by removing this library, and it was not that I simply did not like it,  there were good reasons, why I did it :-)

I hope, you can live with that new persistence solution as I was hoping we could merge it into the master branch next week or so (as long as you are ok with it). Just take a look a the "persistence-refactoring" branch and tell me what you think.

**Comment by soenkenils** [comment]
Another update on the status of the new "persistence" module:

For now, two things can be stored:
-   Testbed configurations as described by the testbed-configurations.xml (tested)
-   Binary images (not fully implemented and untested; DAO and Service operations are still missing)

Next steps would be the implementation of the DAO and Service operations for binary images (the Hibernate annotated BO is already there) and testing of `@Lob` annotation for the byte-array. Also, we have to make sure, that Dozer can map byte-arrays.

**Comment by ichatz** [comment]
By using Gilead you avoid defining each Entity twice... So essentially the same object that is generated by Hibernate is used by Gilead and it is serialized to the client automagically. With Dozer this needs to be done manually...

Transaction management is done on the Hibernate side... the beans generated by Gilead are detected from the transaction. I fully agree with this direction.

In my mind, these two issues are separate. 

Since you also agree on using the Spring framework, I propose to also look into the caching mechanisms. It can help us speed up the look-ups on the various entities (e.g., available nodes) without any programming effort...

**Comment by soenkenils** [comment]
Ioannis, thanks for your comment. I agree, 
1.   mapping transfer objects to persistent objects and 
2.   transaction management 

are two different issues.

Gilead shines for 1) but offers no solution to 2). For 2) I proposed Spring transaction management.

Currently, we only have just two Entities (it might be up to five or so in the future). For such a small number I don't see the need to tie us to a framework like Gilead, which brings so many other dependencies.

Also, I don't see a feasible way of using Gilead and Spring transaction management together.

As I said in my previous post, in terms of application architecture and using layers to decouple (see https://github.com/itm/wiseui/wiki/DesignNotePersistence), in my opinion Gilead offers a non-ideal solution. 

```
 public class ReservationServiceImpl extends PersistentRemoteService 
                                     implements ReservationService {    

    private static final long serialVersionUID = -7715272862718944674L;

    private HibernateUtil gileadHibernateUtil = new HibernateUtil();

    @Inject
    public ReservationServiceImpl() {
        gileadHibernateUtil.setSessionFactory(
                WiseUiHibernateUtil.getSessionFactory());
        PersistentBeanManager persistentBeanManager = 
            new PersistentBeanManager();
        persistentBeanManager.setPersistenceUtil(gileadHibernateUtil);
        StatelessProxyStore sps = new StatelessProxyStore();
        sps.setProxySerializer(new GwtProxySerialization());
        persistentBeanManager.setProxyStore(sps);
        setBeanManager(persistentBeanManager);
    }
     ...
 }
```

Here, Gilead forces you to extend `PersistentRemoteService`. This means our server module has a dependency to persistent-related stuff, which it shouldn't. All persistence code shall be decoupled in the "persistence" module. 

This also means the client currently "sees" persistence code, because the `ReservationService` can be called  from the client. In my opinion persistence shall be hidden from the client and exclusively used by the GWT-RPC services. This is what I tried to sketch in the Persistence Design Note (https://github.com/itm/wiseui/wiki/DesignNotePersistence). 

The new persistence layer offers one simple interface for all persistence-related operations. Thus, the "server" module only needs to now the `PersistenceService` and nothing else (e.g. no `SessionFactory`, no `PersistentBeanManager`, no `StatelessProxyStore`, etc.).

Maybe I'm too much of an idealist :-)

**Comment by mlegenhausen** [comment]
+1 for snommsens ;)

Maybe I can show you more aspects why dozer usage is to preffered:

When using Gilead you have no control over the data that is transfered, cause you have always to transfer all data that is deliverd by Gilead. In many cases you dont want that. When looking at the best pratice guide from GWT, the RPC Service is a part of the GUI! It is not the same like RMI or other Service technologies. In the RPC Service you reduce your data to the amount that is currently needed for the GUI. That means you have to map the data!

Gilead is a framework that reduces your development time (only on the first look), but shows the wrong thinking when using GWT. Your GWT RPC Service is part of the Webtier and not Part of the Application Tier when looking at a 3 tier architecture. This means when it is Tier 3 and it is part of the server side. It is the component where you reduce (map) your data. When looking at normal Web Application programmiering, you dont transfer all your data to the client and reduce it there via javascript. But that is what you doing when using Gilead!

Best Practice Video from Google: http://www.google.com/events/io/2009/sessions/GoogleWebToolkitBestPractices.html

A mapping isn't that hard as it is discribed here. Dozer without any configuration can do so much! A simulated Gilead mapping in Dozer means, you have to copy the class you want to transfer and then write the following line: 

```
MyDto dto = dozer.map(source, MyBo.class);
```

That it and you have all features like transactions! When looking at Gilead the amount of code and disadvantages is much higher.

Another disadvantage is the big persistance to GUI binding, cause every change in the persistance model leads to a change in the GUI!

**Comment by mlegenhausen** [comment]
How is the status of this discussion? Have we found a consensus?

Some addition to my previous post:
Of cause you do not reduce only to the data that is currently displayed. It is always a tradeoff between which data is needed now or later and the general transfer overhead. That is what we doing with the TestbedConfigurations where we transfer the whole object for the TestbedSelection but only the half of the data is needed, because we need all the data in different parts of WiseUi. So it is good to have them as soon as possible on the client side. But to get the chance to scale this tradeoff we need a general mapping mechanism and this is dozer.

**Comment by soenkenils** [comment]
@gakos, @whantana, @ichatz, what do you think? Shall we merge this into master this week?

**Comment by whantana** [comment]
During the development so far I haven't done many stuff with the persistence . Having read the opposing arguments above, I came to agree with snommensens view on the persistence refactoring. Though our code extensibly uses Gilead and requires a great deal of refactoring to get over it, removing it would help decouple server's code and make those tier layers more discrete and easier to implement.
However , considering the meeting at UZL next week and the fact that we are nearly done finishing the code intergration between our repos I suggest moving the persistence module merging into master not this week but next week. Any changes now on the master branch will require tones of refactoring on both server and client side. 

Moreover, I hope this refactoring clears up a lot of things regarding the persistence design. Currently there has been some issues as what goes in or out the persistence model (see the reservation keys issue).
