### ISSUE TITLE
Test error during Maven install

### ISSUE THREAD

**Issue by whantana** [itm/wiseui#25]
Hi , I keep getting this error during "mvn clean install"

---
##  T E S T S

Running eu.wisebed.wiseui.client.util.AuthenticationManagerTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.222 sec <<< FAILURE!

Results :

Tests in error: 
  initializationError(eu.wisebed.wiseui.client.util.AuthenticationManagerTest)

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

Maven tries to run some tests after building the app but it seems that the tests are not even initialized. Does anyone else gets this message or is it just me

**Comment by soenkenils** [comment]
Yes, I had this, too. This should work: https://github.com/itm/wiseui/commit/032f687367b528086afc639672aefaa8d1c72ca9

**Comment by mlegenhausen** [comment]
Seems to work now.

**Comment by soenkenils** [comment]
Ok, nice. I'm closing this issue.
