### ISSUE TITLE
Static code analysis

### ISSUE THREAD

**Issue by ichatz** [itm/wiseui#26]
I have added the PMD and FindBugs code analysis tools.

OMHO, the most serious issues are those reported by FindBugs. Then by PMD, and finally for Checkstyle. Some times Checkstyle can be very pedantic. And some other times PMD may produce cyclic issues.

Anyway, it is a good idea to go through the code and clean up some important, yet simple to fix, issues.

For our convenience, I have added a project under Hudons (the continuous integration tool) [http://ru1.cti.gr/hudson/job/wiseui/] that also executes all the analysis tools and stores the results...

If you wish I can create account -- just send me a mail.

**Comment by mlegenhausen** [comment]
Very good idea. Can you make the reports public? When clicking on the build a can see nothing.

**Comment by soenkenils** [comment]
As @ichatz already added a reference to the Hudson/Jenkins build system in the README file, I will close this ticket.
