### ISSUE TITLE
Create Administration View To Manage Testbed Configurations

### ISSUE THREAD

**Issue by soenkenils** [itm/wiseui#28]
In the new Administration page, the user shall be able to create, read, update, delete testbed configurations. This shall replace the static XML file _testbed-configurations.xml_.

The Administration page shall contain forms to achieve the above tasks. By submitting the forms a persistence operation is triggered on the server side.

**Comment by mlegenhausen** [comment]
Should we edit the testbed-configuration.xml file or should we write it in a database?

**Comment by soenkenils** [comment]
The _testbed-configurations.xml_ shall be completely replaced by managing the testbed configurations and store it in our database. You can use new the `PersistenceService` to store and load testbed configurations. That of course implies, that either you have to work in the 'persistence-refactoring' branch or we have to merge the new persistence into 'master' first...

**Comment by mlegenhausen** [comment]
I would prefer the second... but I can start on designing the view without having any persistence now.
How long would you say until you can merge into the master?

**Comment by mlegenhausen** [comment]
I currently thinking about the design, wouldn't it be better instead of adding a complete new area simply adding a new view button to the TestbedSelection that is called administration? Cause I want to use the ConfigurationView to switch between the different testbeds.

**Comment by soenkenils** [comment]
Sounds fine.

**Comment by mlegenhausen** [comment]
I rethought this, I think a administration view would better fit, so we don't mix up to much the view for the testbed content and the testbed configuration. But I will reuse the components.

**Comment by mlegenhausen** [comment]
How do we determine who is allowed to edit the TestbedCofigurations?

**Comment by soenkenils** [comment]
Good question. For the moment I would say the one, can log in to a testbed via our existing login mechanism shall also be allowed to change the configuration of the testbed. 

But we should certainly think about a more fine-grained access management.

**Comment by mlegenhausen** [comment]
In first instance we should solve this on the server side and simply throwing an exception.

When you mean more fine-grained access management, this will also include a seperated user management for the whole WiseUi?

**Comment by mlegenhausen** [comment]
I will add the gwt-vl framework for form validation: http://sourceforge.net/projects/gwt-vl/
It seems active and make a good looking.

**Comment by mlegenhausen** [comment]
Which fields of TestbedConfiguration are required? And is there a special format for the different fields? Like URLs?

**Comment by mlegenhausen** [comment]
I think we can remove the Administration tab and integrate this party completely in the TestbedList via a popup.

**Comment by mlegenhausen** [comment]
The administration tab is now fully integrated in the testbed list. But currently is the serverside functionality missing.

**Comment by mlegenhausen** [comment]
The task itself is done. Please open issues for bugs.
