### ISSUE TITLE
Should we use yoda conditions in our source code?

### ISSUE THREAD

**Issue by mlegenhausen** [itm/wiseui#29]
I found sometimes yoda conditions in the source: http://united-coders.com/christian-harms/what-are-yoda-conditions
Now the question should we use it as a general source convention? When yes we should add it to checkstyle. Sometimes it looks a little confusing, but is has his advantages.
One of the advantages can be added with checkstyle by preventing asignments in conditions.

**Comment by ichatz** [comment]
I think we should.

**Comment by soenkenils** [comment]
`"myString".equals(stringVariable)` is certainly better than having to check `stringVariable` for `null` first. But I don't know whether this can be configured with Checkstyle. I will evaluate that.

**Comment by soenkenils** [comment]
What we also could do is add convenience checks in a generic class. In the other branch "persistence-refactoring" I also started such a class: https://github.com/itm/wiseui/blob/persistence-refactoring/shared/src/main/java/eu/wisebed/wiseui/shared/common/Preconditions.java.
We could extend this class in this respect.

**Comment by ichatz** [comment]
I think that Checkstyle can support this...

check out the Sun configuration.

**Comment by soenkenils** [comment]
The rule for my above example is already included as `<module name="EqualsAvoidNull"/>` in our existing checkstyle configuration :-)

See https://github.com/itm/wiseui/blob/master/build-tools/src/main/resources/eu/wisebed/wiseui/checkstyle.xml

More on coding style can be found here: https://github.com/itm/wiseui/wiki/CodingStyleDesignNote

Everyone is welcome to contribute and comment on this design note.

**Comment by mlegenhausen** [comment]
And what didi you say for the general usage of `if (null == variable)` ? I think a consistent convention would be good.

**Comment by soenkenils** [comment]
The rationale behind this (switching null and variable) is to avoid mixing up a boolean expression with an assignment, e.g. `if (variable = null)`. But I don't see this danger with modern IDEs and compilers.

![Check for NULL in modern IDEs](http://www.itm.uni-luebeck.de/users/nommensen/wiseui/ide_null_statement.png)

The real issue is avoiding such ugly statements at all :-) This is discussed here: http://stackoverflow.com/questions/271526/how-to-avoid-null-statements-in-java. Also, the NullObject Pattern (http://en.wikipedia.org/wiki/Null%5FObject%5Fpattern) is worth a look.

**Comment by mlegenhausen** [comment]
Sure, but most of the solutions can only be found with intensive code reviewing.

But in general we can go on and use the general syntax where we use `if (variable == null)` instead of `if (null == variable)`!?

**Comment by soenkenils** [comment]
IMHO, it does not matter really much whether we will write `null` first or second. Personally, I prefer the first method for readability reasons. What we have to keep in mind though, is the EqualsAvoidNull rule!

**Comment by bohemian** [comment]
if (variable = null) wont even compile in java, except in the rare edge case of variable being Boolean, in which case the assignment will cause a NPE, and not a silent assignment.
All yoda conditions are useless and bad in java.
