### ISSUE TITLE
Rearrange Experimentation view and activity

### ISSUE THREAD

**Issue by whantana** [itm/wiseui#34]
...in accordance with the changes made in the Luebeck Meeting

**Comment by soenkenils** [comment]
@mlegenhausen @whantana Can you please add some more details about the new Experimentation view (in this issue)?

**Comment by whantana** [comment]
there's a currently a view problem. The experimentation view container when filled with a number of experiments get those experiment panels get smaller and smaller , even though the container is scrollable and can handle multiple components. This is either a style issue or i widget issue since the experiment panels are DockLayoutPanels that tend to be resizable. Overall the view is almost finished

**Comment by whantana** [comment]
Just a question, so far this view displays data related to reservations on testbeds other than the federator testbed which contains multiple urnPrefixes and multiple data . 

Should the experimentation view support multiple urns and reservation keys?
