### ISSUE TITLE
"Show more" link in the WiseML detail view does not work

### ISSUE THREAD

**Issue by pfisterer** [itm/wiseui#39]
Browser Used: Firefox 4
Testbed: Federator

**Comment by soenkenils** [comment]
@mlegenhausen: Have you seen this bug report and can you confirm or clarify this behavior of the "Show more" link?

**Comment by mlegenhausen** [comment]
I can not confirm this behaviour. But it looks like that the show more link is shown even if there is no more data to show. May be this can be confusing.

**Comment by soenkenils** [comment]
Seems like this is not a defect but an user interface issue.

**Comment by pfisterer** [comment]
What does this mean? It doesn't work for me in different browsers (FF4 and Chrome). The same happens on Daniel's Mac.

**Comment by soenkenils** [comment]
The "Show more" belongs to the default GWT tree widget. It works fine for me in Safari/Chrome (Mac) in Hosted Mode and deployed in a Tomcat. 

Maybe this is related to http://code.google.com/p/google-web-toolkit/issues/detail?id=5547.

**Comment by pfisterer** [comment]
Ok, so let's hope for a fix in GWT.
