### ISSUE TITLE
Move all Widgets that are used in different parts of the WiseUi in the widget module

### ISSUE THREAD

**Issue by mlegenhausen** [itm/wiseui#4]
Widgets that can be moved in the widget module:
- DialogBox
- Create a widget for the panels with a title.
- The Utility class for using the dialog class in uiBinder

**Comment by soenkenils** [comment]
Partly solved. The MessageBox widgets were moved to the "widgets" module.

**Comment by mlegenhausen** [comment]
Everything has been moved to the widgets module.
