### ISSUE TITLE
Show an indicator for testbeds the user is logged in

### ISSUE THREAD

**Issue by mlegenhausen** [itm/wiseui#41]
Currently there is no display for showing the user in which testbeds the user is logged in. For this purpose in the testbed list an indicator should be added.

Note: The user is logging in on urn prefix base and not on testbed base!

**Comment by soenkenils** [comment]
I prepared this with a quick hack. But the current solution is non-ideal and has to be improved.

**Comment by iogakos** [comment]
I think a descriptive icon near the cell entry is OK. 

If we want to make it more usable we could emphasize the corresponding testbed entry in the cellList (like an instant green flash/blur), by the time the user successfully authenticating. Something like indicating to the user  "[<-- The testbed you logged in is here/]" and applying a 'tick' icon next to the testbed entry.

**Comment by soenkenils** [comment]
For the time being, please treat this issue with low priority :-)
