### ISSUE TITLE
Actually perform reservations

### ISSUE THREAD

**Issue by soenkenils** [itm/wiseui#43]
With the current version, the WiseUI can display all public reservations in a calendar. But what still has to be done is the reservation of nodes.

I prepared this with a Tree view of the testbed in the Reservation view. This tree view has to be extended with a checkbox (see http://gwt.google.com/samples/Showcase/Showcase.html#!CwCellTree).

The WiseUI reservation panel shall offer the user the possibility to select the nodes he wants to reserve
- on testbed level
- on node group level
- and on node level.

In the calendar the user shall be able to create a new time interval with a double click and associate the selected nodes with this time interval. When this selection of nodes and time is finished, the user shall be able to actually make the reservation on the selected testbed. 

The user can only make a reservation if he is authenticated for the testbed in which he wishes to make the reservation!

**Comment by iogakos** [comment]
+1

Should we double click to determine a time interval for a new reservation or should we handle a click/drag/unclick event?

**Comment by soenkenils** [comment]
@gakos Would you take care of this task?

First, we need the fundamental functionality. Later you can implement the drag event handlers. My idea is to use a pop-up (ReservationEditView; a basic version of this view should already exist) to create and edit reservations. This pop-up can be shown when a time slot in the calendar is double-clicked. There is already a event-handler for this event, which currently only logs that a time-slot was double clicked. This event-handler can be used to show the ReservationEditView pop-up.

**Comment by iogakos** [comment]
@snommensen I am currently working on this.

I also agree on the 'pop-up' idea.

**Comment by soenkenils** [comment]
Ok, nice :-D
