### ISSUE TITLE
Use JavaDB as default persistence configuration

### ISSUE THREAD

**Issue by danbim** [itm/wiseui#47]
It would be nice if one could simply clone WiseUI and either `mvn gwt:run` or `mvn package` the project without having to configure a lot of things. This would lower the effort to get the system up and running. We could use JavaDB (which ships with the JRE) as default persistence layer which should be perfectly fine from a performance point-of-view. That could be overridden by additional configuration files to use more advanced databases such as MySQL.

What do you guys think about this?

**Comment by ichatz** [comment]
This is a nice idea.

Another alternative is HSQL -- also a native Java RDBMS that is fully 
compatible with PErsistence API and has the option to run embedded with 
the VM... so absolutely 0 files.

**Comment by danbim** [comment]
Fine with me. I only think there should be no setup work necessary in shipping configuration :)

**Comment by mlegenhausen** [comment]
+1
An automatic way for loading the test data to the database would be fine too.

**Comment by soenkenils** [comment]
Implemented quick win solution.
