### ISSUE TITLE
Maven License plugin problem.

### ISSUE THREAD

**Issue by whantana** [itm/wiseui#50]
Got latest commit and run on the top level of project (./wiseui)

mvn clean install

and the mvn stops containing this : 

[WARNING] The POM for com.mycila.maven-license-plugin:maven-license-plugin:jar:1.9.1.1-SNAPSHOT is missing, no dependency information available

**Comment by danbim** [comment]
Did you check if maybe just the repository of the dependency was temporarily down or the meta data on the repository is broken? Sometimes this leads to errors like this...

**Comment by soenkenils** [comment]
Thanks. I forgot to change back the plugin version to the official one after experimenting with my own version of the plugin.
