### ISSUE TITLE
Reset nodes functionality

### ISSUE THREAD

**Issue by danbim** [itm/wiseui#52]

**Comment by soenkenils** [comment]
How does this differ from #51? Do we need to trigger the reset function explicitly?

**Comment by danbim** [comment]
Yes, that's another API call and resetting nodes doesn't require to reflash the nodes (which decreases the overall lifetime of the hardware) and works faster.

**Comment by whantana** [comment]
I think it could be implmented easily just like flash functionality on the WiseUI . i think i can make by the M1
