### ISSUE TITLE
Re-use EditReservation{View, Presenter} for Reservation CRUD-operations

### ISSUE THREAD

**Issue by soenkenils** [itm/wiseui#55]
## Re-use Existing Widget `EditReservation`

Currently, we show a different Pop-Up window for creating and deleting reservations. We could re-use the `EditReservation{View, Presenter}` to implement create, read, update and delete ('CRUD') operations for reservations.

The challenge is to find a way to fetch the list of nodes associated to the reservation to show them as "Node Summary" as in the `makeReservation` ('C') case. 

For 'R' the `EditReservationView`'s fields shall be read-only.
## Hint

It looks like the Testbed RS-API only offers operations for 'CRD'. Thus, we have to make two API-calls for 'U', e.g. 'D' and 'C'.

**Comment by whantana** [comment]
hi , you think we can make it by the M1 ? if not should we reassign issue for M2 ?

**Comment by soenkenils** [comment]
Ok, maybe we don't need 'U' for M1. 'C', 'R' and 'D' are already implemented, but a better 'R' would be nice :-)

What I would like to have is the "Node summary" from the 'C' dialog.

**Comment by soenkenils** [comment]
I implemented the re-use of the view. But it's not fully functional, yet.

Currently I'm resurrecting the 'D'-functionality.

@master-lincoln Would you implement the 'U'-functionality?

**Comment by master-lincoln** [comment]
Done... See commit 86af7bdd14389fd05ed37ea8a110935d94db8c2c
