### ISSUE TITLE
Login-Indicator (orange/green dot) for each testbed displays incorrect status

### ISSUE THREAD

**Issue by pfisterer** [itm/wiseui#58]
The Login-Indicator (orange/green dot) for each testbed displays a incorrect status. For instance, for an active login with the UZL testbed (prefix: wisebed:uzl:), the dot is green (which is correct). However, a green dot is also shown for the Federator (which is wrong, since it comprises multiple prefixes and hence we don't have a login for the others).

**Comment by soenkenils** [comment]
Yes, this is a known bug, which still persists due to low prioritization :-) However, as you specified, M2 is the correct milestone to solve this.

**Comment by master-lincoln** [comment]
I have solved it. Will upload later...
One Problem was in the WiseML descriptor of the Federator: The urn prefixes list was only containing uzl and the other problem was in the AuthenticationManager
