### ISSUE TITLE
Give Philipp a Nice Welcome :-)

### ISSUE THREAD

**Issue by soenkenils** [itm/wiseui#59]
Dear Team,

please welcome our newest WiseUI-Team member Philipp (on GitHub he is @master-lincoln)! 

Philipp is a student at the University of Lübeck and will work with us for the next two months.

So, Philipp, welcome! Nice to have you on board. And now I will create some real issues for you ;-)

Best regards,
Sönke

**Comment by mlegenhausen** [comment]
Welcome Philipp!

**Comment by ichatz** [comment]
WELCOME !!

**Comment by danbim** [comment]
Welcome aboard!

**Comment by whantana** [comment]
welcome ^^

**Comment by master-lincoln** [comment]
Thanks together...
I guess I can close this now.
