### ISSUE TITLE
Cannot Build Project

### ISSUE THREAD

**Issue by master-lincoln** [itm/wiseui#65]
Currently `mvn clean install` gives me

<pre>
[INFO] ------------------------------------------------------------------------
[INFO] Building WiseUI - Server
[INFO]    task-segment: [clean, install]
[INFO] ------------------------------------------------------------------------
[INFO] [clean:clean {execution: default-clean}]
[INFO] Deleting directory /media/WISEBED/WISEBED/workspace/wiseui/server/target
[INFO] [resources:resources {execution: default-resources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 13 resources
[INFO] Copying 2 resources
[INFO] [compiler:compile {execution: default-compile}]
[INFO] Compiling 13 source files to /media/WISEBED/WISEBED/workspace/wiseui/server/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /media/WISEBED/WISEBED/workspace/wiseui/server/src/main/java/eu/wisebed/wiseui/server/controller/ExperimentController.java:[227,15] cannot find symbol
symbol  : method setChildren(java.util.List)
location: class eu.wisebed.wiseml.model.trace.Trace
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Compilation failure
/media/WISEBED/WISEBED/workspace/wiseui/server/src/main/java/eu/wisebed/wiseui/server/controller/ExperimentController.java:[227,15] cannot find symbol
symbol  : method setChildren(java.util.List)
location: class eu.wisebed.wiseml.model.trace.Trace
</pre>

**Comment by whantana** [comment]
Today we added "setChildren" to the WiseML JibX lib the experimentation servlet uses. They maintain it here in RACTI and pushed at their repo this addition at https://github.com/ichatz/wiseml today. It will be uploaded at the maven repo soon , you can also pull it . Please close this issue when fixed.

**Comment by soenkenils** [comment]
The new version seems to be available now in the maven repository.

**Hint:** Use `mvn clean install -U` to enforce updates of dependencies and plugins.

In this particular case it would have been better to wait with your push until the dependency was available. In general, please only push code that compiles to ensure that everyone can work with the latest version from the repository.

**Comment by ichatz** [comment]
Hudson can built the project without any problem...
