### ISSUE TITLE
"mvn gwt:run" does not work properly since update to GWT 2.3.0

### ISSUE THREAD

**Issue by soenkenils** [itm/wiseui#67]
I don't know why exactly, but `mvn gwt:run` does not work properly (at least on my computer) since I changed the GWT version to 2.3.0. The error message was:

```
 javax.validation.ValidationException: Unable to find a default provider
```

Thus, I added a Hibernate Provider dependency to the `persistence`-module in `persistence/pom.xml`:

```
 <!-- Hibernate validator for bean validation -->
 <dependency>
     <groupId>org.hibernate</groupId>
     <artifactId>hibernate-validator</artifactId>
     <version>4.1.0.Final</version>
 </dependency>
```

With that change `mvn gwt:run` works again.

Did someone experience something similar?

**Comment by master-lincoln** [comment]
I can confirm this. Your fix also worked for me.

Would you please commit that change?

Update:
I now get the following warning inside my browser when starting:

<pre>
ERROR: Possible problem with your *.gwt.xml module file.
The compile time user.agent value (safari) does not match the runtime user.agent value (gecko1_8). Expect more errors.
</pre>

And I lost the ability to start from eclipse.
Error:

<pre>
1) Error in custom provider, org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [persistence-spring-config.xml]: Invocation of init method failed; nested exception is org.hibernate.HibernateException: Unable to get the default Bean Validation factory
  at eu.wisebed.wiseui.server.WiseUiGuiceServletModule.providePersistenceService(WiseUiGuiceServletModule.java:72)
  at eu.wisebed.wiseui.server.WiseUiGuiceServletModule.providePersistenceService(WiseUiGuiceServletModule.java:72)
  while locating eu.wisebed.wiseui.api.PersistenceService
    for parameter 0 at eu.wisebed.wiseui.server.rpc.TestbedConfigurationServiceImpl.<init>(TestbedConfigurationServiceImpl.java:40)
  at eu.wisebed.wiseui.server.rpc.TestbedConfigurationServiceImpl.class(TestbedConfigurationServiceImpl.java:31)
  while locating eu.wisebed.wiseui.server.rpc.TestbedConfigurationServiceImpl
</pre>
