### ISSUE TITLE
Experimentation View: Don't display secret reservation keys of other users reservations

### ISSUE THREAD

**Issue by danbim** [itm/wiseui#69]
Currently all reservations are shown including their SRK even if the reservations are owned by another user.

**Comment by soenkenils** [comment]
Which version do you refer to? The deployed wiseui-beta? I was just trying it and cannot confirm this. 

But this could be done, if we weren't filtering the confidential reservation data in the client. Why does the TR returns all the secret reservation keys in the first place?

**Comment by danbim** [comment]
Yes, the currently deployed wiseui-beta does it. Also, the deployed version is only optimized for Safari (I get an error message).

**Comment by soenkenils** [comment]
For which testbed, UZL?

**Comment by danbim** [comment]
Yes

**Comment by soenkenils** [comment]
Tried it again. Still cannot confirm. Do you have a screenshot so I can see what might by wrong?

**Comment by danbim** [comment]
Screenshot attached!

Am 20.06.11 16:23, schrieb snommensen:

> Tried it again. Still cannot confirm. Do you have a screenshot so I can see what might by wrong?

**Comment by soenkenils** [comment]
Sorry, but I cannot find the attachment. Can you send it to me via mail or skype?

**Comment by danbim** [comment]
Updated the tickets description: this bug happens in the experimentation view.

**Comment by soenkenils** [comment]
Fixed.
