### ISSUE TITLE
Experimentation View: Exception on binary image upload

### ISSUE THREAD

**Issue by danbim** [itm/wiseui#70]
When trying to upload a binary image to be flashed to the nodes I get the following exception (on wiseui-beta deployment):

```
The upload was canceled because there was an error in the server.
Server error is:

org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Cannot open connection
```

**Comment by soenkenils** [comment]
This was due to a lost database connection as MySQL is configured to close connections after 8 hours. I added the `autoReconnect=true` parameter to the JDBC connection string, which should fix this issue.
