### ISSUE TITLE
Hudson build failed

### ISSUE THREAD

**Issue by ichatz** [itm/wiseui#71]
(please do not close this task so that hudson can send notifications to this task thread)

**Comment by soenkenils** [comment]
Do you know how I can trigger a Hudson build every time someone pushes to GitHub? I would also like to deploy the resulting war-file to a Tomcat automatically. Can this be configured?

**Comment by ichatz** [comment]
I have configured that a couple of days ago... now I think that it is working.

Essentially it is polling git every hours to see if there is anything new to pull, and then builds...

Then you can get tweets of the outcome if you follow the ru1hudson account.

Now I want to use the e-mail of this thread to post notifications on the outcome of the builds.

**Comment by ichatz** [comment]
Yes, you can also configure it to be deployed automatically via scp.

**Comment by soenkenils** [comment]
Can we close this? Seems not to be updated by Hudson...
