### ISSUE TITLE
Implement a testbed heartbeat table

### ISSUE THREAD

**Issue by pfisterer** [itm/wiseui#72]
Implement a new WiseUI tab that displays a status table that displays an up-to-date status of all configured testbeds. The status should be determined by invoking methods of the APIs and check for correct behaviour.

The following data should be displayed (e.g., using a table):
- Overall status (e.g., using sunny, cloudy, thunderstorm icons)
- Description  
- URN prefix(es)
- SNAA API Web Service Endpoint URL
- SNAA API status
- Reservation API (RS) Web Service Endpoint URL
- RS API status
- iWSN Session Management API Endpoint URL
- iWSN Session Management status

**Comment by danbim** [comment]
Do we still need this?
