### ISSUE TITLE
Add Google Protobuf Support

### ISSUE THREAD

**Issue by soenkenils** [itm/wiseui#8]
The usage of WebService calls shall be complemented by Google Protobuf as they provide better performance.

**Comment by mlegenhausen** [comment]
Were can be found the API for Protobuf?

**Comment by soenkenils** [comment]
This could be it: https://github.com/itm/testbed-runtime/tree/master/protobuf-api

**Comment by mlegenhausen** [comment]
It should not be migrated. It should be an alternative rpc method for the webservice, cause not all tesbed webservices support protobuf.

**Comment by soenkenils** [comment]
Done.
