### ISSUE TITLE
Cannot build current version

### ISSUE THREAD

**Issue by soenkenils** [itm/wiseui#9]
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/soenke/Code/wiseui/client/src/main/java/eu/wisebed/wiseui/client/util/QuickHull.java:[204,33] cannot find symbol
symbol  : constructor Coordinate(eu.wisebed.wiseui.shared.wiseml.Coordinate)
location: class eu.wisebed.wiseui.shared.wiseml.Coordinate
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.067s
[INFO] Finished at: Tue Mar 08 11:11:42 CET 2011
[INFO] Final Memory: 18M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project client: Compilation failure
[ERROR] /Users/soenke/Code/wiseui/client/src/main/java/eu/wisebed/wiseui/client/util/QuickHull.java:[204,33] cannot find symbol
[ERROR] symbol  : constructor Coordinate(eu.wisebed.wiseui.shared.wiseml.Coordinate)
[ERROR] location: class eu.wisebed.wiseui.shared.wiseml.Coordinate
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by mlegenhausen** [comment]
I can not reproduce this error.
Try to reinstall the shared project alone and try again.

**Comment by soenkenils** [comment]
Ok, found it.
